version: '3'

services:
  request_dicovery:
    restart: always
    image: node-web-app:test
    build: Dockerfile
    env_file: env.conf
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
    ports:
      - "80:8080"